### ISSUE TITLE
Remove adapter from ioBroker admin > Objects > Settings

### ISSUE THREAD

**Issue by Mic-M** [oweitman/ioBroker.rssfeed#2]
See here: https://forum.iobroker.net/topic/32134/gel%C3%B6st-wie-adapter-ausblenden-bei-objekte-einstellungen

Same for the rss adapter:
![rss_x](https://user-images.githubusercontent.com/39859059/79500013-11933d80-802c-11ea-9cba-1b27e889cd69.png)

Since it looks like you do not need this feature, you can deactivate as follows: https://forum.iobroker.net/post/413450

**Comment by oweitman** [comment]
fixed in v0.0.28
