### ISSUE TITLE
Error Message in Log looking for words.js

### ISSUE THREAD

**Issue by jack-blackson** [oweitman/ioBroker.rssfeed#21]
Hello!

During checking some other errors in the developer console in firefox, when running my vis, I found this error message:
![grafik](https://user-images.githubusercontent.com/13975634/137270797-cb027062-c14f-446e-ad1f-d3523247fca4.png)

It is not creating any problem for me for now, but probably you have the chance to fix it - or let me know what I am doing wrong.

JS Version: 3.3.18
Adapter Version: 0.9.0
Firefox Version: 93.0

**Comment by oweitman** [comment]
fixed
