### ISSUE TITLE
Request: Set maximum age for articles

### ISSUE THREAD

**Issue by 1337gut** [oweitman/ioBroker.rssfeed#4]
Hi, it would be nice to be able to set a max age for articles, i.e. only for the last hours or this day.

**Comment by oweitman** [comment]
Hi.
this is easy with a slightly changed template.
The 3rd line calculates the diff between now and the article-date (pubdate).
the result was in milliseconds. in this example i calculate the diff in minutes (1000*60) an show the article only for the last 100 minutes

```
<%= meta.title %> 
<% articles.forEach(function(item){ %><br>
<% if (((Date.now() - new Date(item.pubdate)) / (1000*60)) < 100) { %><br>
<%- ((Date.now() - new Date(item.pubdate)) / (1000*60)) %><br>
<p><small><%- vis.formatDate(item.pubdate, "TT.MM.JJJJ SS:mm") %> xxx <%- item.pubdate %></small></p>
<h3><%- item.title %></h3>
<p><%- item.description %></p>
<div style="clear:both;" />
<% } %>
<% }); %>

```
