### ISSUE TITLE
Feed wird im Browser nicht angezeigt

### ISSUE THREAD

**Issue by MrSnatz** [oweitman/ioBroker.rssfeed#5]
Hallo,
ich habe alles nach der Anleitung installiert. Im VIS Editor wird auch alles richtig angezeigt. Nur im Fully Browser auf meinem Fire HD und auf dem desktop unter Chrome wird nichts angezeigt.
Mein Iobroker und alle Adapter sind up to date. Mein JS Controller hat die version 3.1.6

![feed_editor](https://user-images.githubusercontent.com/51195705/100860482-dba6aa80-3490-11eb-9683-65dd99295e65.png)
![feed_runtime](https://user-images.githubusercontent.com/51195705/100860487-dd706e00-3490-11eb-856d-8a4751c31eef.png)

**Comment by oweitman** [comment]
Teile mir bitte die genaue RSS-Feed Url mit. Dann stelle ich das mal nach.
Wie ich sehe verwendest du das Marquee Widget?

**Comment by MrSnatz** [comment]
Hier der verwendete Feed http://www.tagesschau.de/xml/rss2/
![Unbenannt](https://user-images.githubusercontent.com/51195705/101276275-fdaf6e00-37ab-11eb-8623-1691b87f12c7.png)

**Comment by oweitman** [comment]
hm, den hab ich auch bei mir laufen und in deinem Fehlerfenster sehe ich keine besonderen Fehler, die das Widget betreffen, auch wenn es da insgesamt 11 Fehler gibt, von denen ich nur 2 in der Liste sehe.
Als nächstes müsste man schauen, ob die html-Inhalte überhaupt an der Stelle eingefügt wurden. Das kann man ebenfalls mit den Developer Tools machen, aber da muss man sich ein wenig damit auskennen.
Ich vermute ein Problem mit CSS, kannst du bitte im vis editor für dieses Widget explizit mal eine weiße Schriftfarbe einstellen?

**Comment by MrSnatz** [comment]
Ich habe den Fehler gefunden. Manchmal ist es so einfach das man es nicht sieht. Ich hatte im VIS Editor den Bereich Sichtbarkeit aktiviert. nach Deaktivierung wird es jetzt auch auf dem Tablet angezeigt. Es läuft wunderbar, kein stottern oder ähnliches. Tolle Arbeit von dir. Kann ich dir bei PayPal ein bisschen Kaffeegeld schicken? Habe schon länger nach so einem Feed gesucht.

**Comment by oweitman** [comment]
Nicht unbedingt nötig, aber wenn du willst gerne hier: weitmann321@gmail.com
Schön das dir der Adapter gefällt.
Im Forum findest du den eigentlichen Support Thread https://forum.iobroker.net/topic/31294/test-adapter-rssfeed-v0-0-x
und auch meine anderen Adapter.
