### ISSUE TITLE
https://raw.githubusercontent.com/oweitman/ioBroker.rssfeed/main/admin/rssfeed.png missing

### ISSUE THREAD

**Issue by mcm1957** [oweitman/ioBroker.rssfeed#54]
**Describe the bug**  
The standard icon referenced at release 2.6.1 (currently availbale in repo) has vanished. So browserconsole logs an error and ion icon is shown instead of rss icon:

https://raw.githubusercontent.com/oweitman/ioBroker.rssfeed/main/admin/rssfeed.png - Error 404

**To Reproduce**  
Check admin adapterpage - no rss ison will be shown
Activate browser console and check for errors when listeing the adapter

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/28575778/220670199-7ede9364-209c-43ca-866a-ba386394e24b.png)

**Versions:**  
 - Adapter version: 2.6.1 

**Additional context**  
Note that iob admin references the contents of github directly. So its required to keep icons referenced insode previous io-package.json files.

Adaptercheck reports:

[E112] extIcon must be the same as an icon but with github path
[E125] External icon not found under URL: https://raw.githubusercontent.com/oweitman/ioBroker.rssfeed/main/admin/rssfeed.png
[E510] "/admin/i18n/uk/translations.json" or "admin/i18n/uk.json" not found, but admin support is declared
[E605] No actual year found in copyright. Please add "Copyright (c) 2023 oweitman <oweitman@gmx.de>" at the end of README.md

Thanks for restoring the original icon

**Comment by GermanBluefox** [comment]
Fixed in 2.8.2. the valid path is https://raw.githubusercontent.com/oweitman/ioBroker.rssfeed/master/admin/rssfeed-logo.png

**Comment by oweitman** [comment]
v2.9.2 now avail on npm and latest repo
