### ISSUE TITLE
VIS nur noch in Englisch nach Update dieses Adapter auf v2.8.1

### ISSUE THREAD

**Issue by somansch** [oweitman/ioBroker.rssfeed#57]
Nach Update auf v.2.8.1 kann man in der VIS nicht mehr auf eine andere Sprache wechseln. Es wird immer die englische Oberfläche angezeigt.

Mit v2.6.1 existiert dieses Problem nicht!

**Comment by oweitman** [comment]
Ok muss ich schauen.
Allerdings hat ein Adapter auf die Spracheinstellungen von vis.
Welche vis Version setzt du ein?

**Comment by somansch** [comment]
Nutze vis v1.4.16

**Comment by GermanBluefox** [comment]
Fixed in 2.8.2

**Comment by oweitman** [comment]
v2.9.2 now avail on npm and latest repo
