### ISSUE TITLE
Error Message in Log looking for words.js 

### ISSUE THREAD

**Issue by bahnuhr** [oweitman/ioBroker.rssfeed#58]
https://github.com/oweitman/ioBroker.rssfeed/issues/21

Habe eben auf 2.7.0 upgedatet

Die Fehlermeldung kommt immer noch.

**Comment by GermanBluefox** [comment]
Fixed in 2.8.2

**Comment by oweitman** [comment]
v2.9.2 now avail on npm and latest repo
