### ISSUE TITLE
Cannot remove adapter "vis", because instance "rssfeed.0" depends on it!

### ISSUE THREAD

**Issue by Karl-Heinz-Mayer** [oweitman/ioBroker.rssfeed#62]
Ichn kann vis nicht löschen, solange rssfeed installiert ist:

`$ iobroker del vis
Delete adapter "vis"
Cannot remove adapter "vis", because instance "rssfeed.0" depends on it!
ERROR: Process exited with code 47`

Ich nutze den rssfeed aber um feeds von Regionalzeitungen auf iQontrol zu zeigen. Klar stellt der Adapter auch ein Widget zur verfügung, aber die muss man ja nicht nutzen.

**Comment by GermanBluefox** [comment]
Fixed in 2.8.2

**Comment by mcm1957** [comment]
Still NOT fixed.
Please merge existing PR !

**Comment by oweitman** [comment]
fixed in v2.9.2, version is avail on npm
