### ISSUE TITLE
extIcon url is not correct

### ISSUE THREAD

**Issue by klein0r** [oweitman/ioBroker.rssfeed#63]
https://github.com/oweitman/ioBroker.rssfeed/blob/11fc3d443148a58c1739db2797a57befefe7b4a4/io-package.json#L240

- `master` instead of `main`
- `rssfeed-logo.png` instead of `rssfeed.png`

`https://raw.githubusercontent.com/oweitman/ioBroker.rssfeed/master/admin/rssfeed-logo.png`

**Comment by GermanBluefox** [comment]
Fixed in 2.8.2

**Comment by klein0r** [comment]
Nothing has been changed in this repo

**Comment by oweitman** [comment]
please recheck.

icon/extIcon/name+path of icon file now in sync
but adapter checker  still complains
