### ISSUE TITLE
Please SYNC adapter Repo to current LATEST 

### ISSUE THREAD

**Issue by mcm1957** [oweitman/ioBroker.rssfeed#66]
Currently this adapter is listed with version 2.8.2 at npmjs while this repository is at level 2.70 (2 years older).

The effective adapter code provided to users is based on fork https://github.com/GermanBluefox/ioBroker.rssfeed.
There is a PR (https://github.com/oweitman/ioBroker.rssfeed/pull/55) to sync created by bluefox.

Please resync as fast as possible as this situation is blocking update of stable repository and is inaczeptable for latest repository too.
If you do not plan to maintain this repo, we can adapt the repository links to the real source of the adapter.

If you have any questions on how to synchronize, please contact @GermanBluefox 

**Please react  until 07.06.2024 as we could decide to change repository entries if no action / reaction occures**

**Comment by oweitman** [comment]
iobroker.rssfeed 2.9.1 is available on npm.js
