### ISSUE TITLE
Feed wird nicht mehr angezeigt mit 3.1.0

### ISSUE THREAD

**Issue by bahnuhr** [oweitman/ioBroker.rssfeed#93]
Hallo,
habe upgedatet auf 3.1.0 
Nun wird in der VIS der feed nicht mehr angezeigt.
Es kommt nur:
![image](https://github.com/user-attachments/assets/32c855c6-e166-4ef1-9488-d1e566d26536)

**Comment by oweitman** [comment]
Ja, bresking Change mit 3.0
https://github.com/oweitman/ioBroker.rssfeed?tab=readme-ov-file#300-2024-07-24

**Comment by bahnuhr** [comment]
Ja, das hab ich gelesen.
Aber mit dem widget 3 funktioniert es auch nicht.

**Comment by bahnuhr** [comment]
Nachtrag:
Im Widget 2 hatte ich folgendes:
DP: rssfeed.0.Nachrichten.ntv
und als rss Vorlage:
`<style>
.myrss img {
  max-width: 200px;
  max-height: 110px;
}
.myrss {
  
  -webkit-columns: 200px 3;
  -moz-columns: 200px 3;
  columns: 200px 3;
}
.article {
  -webkit-column-break-inside: avoid;
  page-break-inside: avoid;
  break-inside: avoid;
}
</style>
<div class="myrss">
<%= meta.title %> 
<% articles.forEach(function(item){ %>
<div class="article">
<p><small><%- vis.formatDate(item.pubdate, "TT.MM.JJJJ SS:mm") %></small></p>
<h3><%- item.title %></h3>
<p><%- item.description %></p>
<div style="clear:both;" />
</div>
<% }); %>
</div>
`

**Comment by bahnuhr** [comment]
habs hinbekommen
